### ISSUE TITLE
Issues building

### ISSUE THREAD

**Issue by Sciman101** [FlutterTal/godot_ggpo#8]
I'm not very familiar with building using SCons, and with there not being much documentation I'm having a hard time figuring out what I'm doing wrong. Specifically, what files go where with regards to the 'sdk' folder. Right now I have the contents of the 'src' folder from ggpo in `modules/godotggpo/sdk`, and the GGPO.lib file in `modules/godotggpo/sdk/bin`, but I have a feeling this isn't right - not to mention it isn't building successfully.
(It's giving me `GGPO.lib(synctest.obj) : error LNK2001: unresolved external symbol __imp_puts`)
Can someone point me in the right direction? I'm trying to build with Godot 3.2.3.

**Comment by FlutterTal** [comment]
So basically, you simply need to put ggponet.h in `modules/godotggpo/sdk/include` and GGPO.lib in `modules/godotggpo/sdk/lib`. Everything should be presented in the `config.py` if you need help. Then you can use SCons with the command I presented in the readme.

Also after you did it, don't forget to put the GGPO.dll in the same folder than your godot executable. Otherwise, godot won't open.

**Comment by Sciman101** [comment]
Gotcha, I ended up actually using the SDK you provided as a release, though I'll try that too. One other thing, though - where do you get GGPO.dll from? I can't find it in either my godot_ggpo or ggpo folder

**Comment by FlutterTal** [comment]
Normally, when you try to build GGPO with CMake, you should tell CMake that you want to build the library as a shared library. That way, when you wanna build GGPO, it will give you the .lib and .dll files.

**Comment by Sciman101** [comment]
Ahh, I see - thanks for your patience, I'll let you know if I'm able to get something off the ground with this
